apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: booking-dev
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: dev/microservices/postgres
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: dev/microservices/postgres
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: dev/microservices/postgres
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: dev/microservices/postgres
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: dev/microservices/postgres
        property: DB_PASSWORD