apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    {{- include "booking.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:   # 👈 removed host (important for ALB DNS access)
      paths:

      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-user
            port:
              number: 3002

      - path: /api/search
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-search
            port:
              number: 3003

      - path: /api/book
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-book   # ✅ FIXED
            port:
              number: 3001

      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-frontend
            port:
              number: 3000