{{- range $service := list "book" "user" "search" "frontend" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-{{ $service }}
  labels:
    {{- include "booking.labels" $ | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ index $.Values $service "roleArn" | default "" }}
{{- end }}