apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prod
data:
  NODE_ENV: "production"
  SEARCH_URL: "http://search-service:3000"
  RESERVATION_URL: "http://reservation-service:3001"
  USER_URL: "http://user-service:3002"