apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-search
  labels:
    {{- include "booking.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.search.replicas }}
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: {{ .Values.image.repository }}/search:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5