#ArgoCD applications for both envs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booking-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SurendraKumar17/microservices-gitops-platform
    targetRevision: develop
    path: k8s/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booking-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SurendraKumar17/microservices-gitops-platform
    targetRevision: main
    path: k8s/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
