global:
  registry: 635457411372.dkr.ecr.us-east-1.amazonaws.com
  env: dev

frontend:
  replicas: 1
  maxReplicas: 4
  tag: "will-be-replaced-by-ci"
  roleArn: ""              # add IRSA role ARN if frontend needs AWS access

book:
  replicas: 1
  maxReplicas: 4
  tag: "will-be-replaced-by-ci"
  roleArn: ""

search:
  replicas: 1
  maxReplicas: 4
  tag: "will-be-replaced-by-ci"
  roleArn: ""

user:
  replicas: 1
  maxReplicas: 4
  tag: "will-be-replaced-by-ci"
  roleArn: ""

postgres:
  host: "postgres"
  user: "postgres"

ingress:
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP