global:
  registry: 635457411372.dkr.ecr.us-east-1.amazonaws.com
  env: dev
frontend:
  tag: dev-c2b5cf1e
reservation:
  tag: develop-147289fc
search:
  tag: develop-772597ae
user:
  tag: develop-0b338d54
