global:
  registry: 635457411372.dkr.ecr.us-east-1.amazonaws.com
  env: dev
frontend:
  tag: dev-beb13ec9
reservation:
  tag: develop-147289fc
search:
  tag: dev-beb13ec9
user:
  tag: develop-0b338d54
